### ISSUE TITLE
Can't figure out how to use standard behavior alongside .generateVariables() in gulp

### ISSUE THREAD

**Issue by Splendorr** [notiv-nt/postcss-media-functions#5]
Hello! Thanks for the great plugin and for your time looking at this. I can't get both the inline declarations *and* generated variables to work at the same time. I'm hoping I just don't understand the syntax, and that it's possible to use both. Here's what I've tried so far.

I'm using 
Node v12.20.0,
"gulp": "4.0.2",
"postcss": "8.2.1",
"postcss-media-functions": "^2.0.1",
"precss": "^4.0.0",
"sugarss": "^3.0.3"

After defining my options,

```
const media_options = {
    // Defaults:
    from: 'from',
    to: 'to',
    // Required
    sizes: {
        sm: '576px',
        md: '768px',
        lg: '992px',
        xl: '1200px',
        xxl: '1500px',
    },
}
```

I can get one or the other of the following to work:
```
require('postcss-media-functions')(media_options)
```
Which lets me use the standard inline declarations, eg `padding: 0 24px from-lg(0 48px)`.

or
```
require('postcss-media-functions')
    .generateVariables(media_options, 'scss')
```
which lets me use the scss-style $from-md variables.

However, if I run `.generateVariables(media_options, 'scss')`, the normal inline calls stop working. I can't figure out how to use both. I've tried

```
require('postcss-media-functions')
    (media_options)
    .generateVariables(media_options, 'scss' /* default, [scss, sass, stylus, less] */)
```
but this produces an error on running gulp:
```
TypeError: require(...)(...).generateVariables is not a function
    at Object.<anonymous> (/Users/nsplendorr/Code/insert-credit-2021-ghost/content/themes/insertcredit/gulpfile.js:38:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireOrImport (/Users/nsplendorr/.fnm/node-versions/v12.20.0/installation/lib/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/nsplendorr/.fnm/node-versions/v12.20.0/installation/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/nsplendorr/.fnm/node-versions/v12.20.0/installation/lib/node_modules/gulp-cli/index.js:211:24)
```
    
Whereas if I reverse the call:
```
require('postcss-media-functions')
    .generateVariables(media_options, 'scss' /* default, [scss, sass, stylus, less] */)
    (media_options)
```
I get this error:
```
TypeError: root.prepend is not a function
    at /Users/nsplendorr/Code/insert-credit-2021-ghost/content/themes/insertcredit/node_modules/postcss-media-functions/index.bundle.js:1:2182
    at Object.<anonymous> (/Users/nsplendorr/Code/insert-credit-2021-ghost/content/themes/insertcredit/gulpfile.js:38:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireOrImport (/Users/nsplendorr/.fnm/node-versions/v12.20.0/installation/lib/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/nsplendorr/.fnm/node-versions/v12.20.0/installation/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
```

Thanks again!

**Comment by Splendorr** [comment]
After posting this, I was able to run both by requiring the plugin twice, once for each function. So,

```
require('postcss-media-functions')
    (media_options),
require('postcss-media-functions')
    .generateVariables(media_options, 'scss' /* default, [scss, sass, stylus, less] */),
```

appears to let both the inline declarations and scss-style vars work! This doesn't *feel like* the intended solution, but I suppose if it's just running two different functions sequentially, there's no reason this can't work!

Is there another way I should do this?

**Comment by notiv-nt** [comment]
@Splendorr `generateVariables` is a function only for generating variables for pre-processors, it **must** be used before sass
If you're using scss, you need 3 steps, something like this:

```javascript
function gulpCss() {
  const mediaOptions = {
    sizes: {
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
    },
  };

  const preSass = [
    require('postcss-media-functions').generateVariables(mediaOptions, 'scss'),
    // ...
  ];
  
  const postSass = [
    require('postcss-media-functions')(mediaOptions),
    // ...
  ];

  return gulp
    .src('src')

    // 'add' variables to your code
    .pipe(_.postcss(preSass, { parser: require('postcss-scss') }))
    
    // sass is using them here
    .pipe(_.sass({ outputStyle: 'expanded' }).on('error', _.sass.logError))
    
    // and here just plain functions 'from-xl' / 'to-xl' ...
    .pipe(_.postcss(postSass))

    .pipe(gulp.dest('dest'))
};
```

https://github.com/notiv-nt/gulp-builder/blob/master/gulpfile.js#L89
